### ISSUE TITLE
Underscore-Bug - Worlds with underscores in name don't work

### ISSUE THREAD

**Issue by coreequip** [DSlyDog/Universes-Rewritten#9]
Hi Andrew,

you don't seem to have a current repository for your `universes-nether` plugin so I put the bug report here. Hope that's okay.

## The bug

Precondition: Let's say you have two worlds
- `dreamland` and
- `dreamland_new`

and their corresponding nether worlds
- `dreamland_nether` and
- `dreamland_new_nether`

(Do you see the issue already? 😉)

The `Universe-Nethers v2.6-beta4` has in the `net.whispwriting.universenethers.Events.NetherPortalHandler` class in line 27 following:

`String overWorldName = worldName.substring(0, worldName.indexOf("_"));`

This will cause that when you travel from `dreamland_new_nether` to the "overworld" you end up in `dreamland` (instead of `dreamland_new`). Because the plugin cuts of the name at the first appearance of a underscore.

## The Fix

Please use `worldName.substring(0, worldName.lastIndexOf("_"));`

There are more lines to cut of the suffix from the world name. Please check all of them.

Thank you for this awesome plugin. This makes our little minecraft hideout a better place. ❤️ 

PS: I would have liked to send you a pull request, but unfortunately you don't have this repository online or I haven't found it.

**Comment by DSlyDog** [comment]
Hiya, thanks so much for this. I probably would never have realized that little mistake. For the most part, people with naming schemes like that haven't had any issues, or at least haven't reported any issues, so I never thought to look. 

As for the repository, yeah, that's just me being slow. I'll make repositories for the extension plugins someday. Unfortunately I am away this week, and I forgot to grab the external drive I have the projects on before I headed out the door.

**Comment by DSlyDog** [comment]
Implemented the fix (still need to test) so marked as resolved.
